version: "3.5"
services:
  postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: test_db
    volumes:
      - pg_volumn:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pg_volumn:
